akalburg@Zeus:~$ python2.7
Python 2.7.2 (default, Jul 29 2011, 11:50:54) 
[GCC 3.4.6 20060404 (Red Hat 3.4.6-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/2.7.2/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/python/2.7.2/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
>>> 
>>> 
akalburg@Zeus:~$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> 


I with out doing the sys.path manipulations on every run i can even fix this. I believe module add on the cluster is broken. 

And also, home directory are on remote file server, and is shared between all the cluster machines. 
So I have to use different dir structure for each replica to test. As i want individual replicas to be updated.

So different replica different directory structure and on that i have threads to worry about!!!...  
